# ============================================================
# FOREST PLOT SCRIPT -- META-ANALYSIS
# Direct EVT vs. Bridging Therapy for Acute LVO Ischemic Stroke
# Generated by: Statistician Agent
# Date: 2026-02-26
# ============================================================

# --- 0. Setup & Package Checks --------------------------------

ensure_packages <- function(pkgs) {
  for (pkg in pkgs) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      install.packages(pkg, repos = "https://cloud.r-project.org")
    }
    library(pkg, character.only = TRUE)
  }
}

ensure_packages(c("metafor", "meta"))

# --- 1. Data Input --------------------------------------------

# 1.1 Primary outcome: 90-day mRS 0-2 (functional independence)
# Direct EVT = intervention group; Bridging = control group
# Effect direction: OR > 1 favors Direct EVT

study <- c(
  "DIRECT-MT (Yang 2020)",
  "DEVT (Zi 2021)",
  "MR CLEAN-NO IV (LeCouffe 2021)",
  "SKIP (Suzuki 2021)",
  "SWIFT DIRECT (Fischer 2022)",
  "DIRECT-SAFE (Mitchell 2022)"
)

year <- c(2020, 2021, 2021, 2021, 2022, 2022)

# mRS 0-2 events
e_evt  <- c(119, 63, 138, 61, 131, 84)   # Direct EVT
n_evt  <- c(327, 116, 270, 103, 201, 146) # Direct EVT total
e_br   <- c(121, 55, 139, 58, 127, 82)   # Bridging
n_br   <- c(329, 118, 264, 101, 207, 149) # Bridging total

# 1.2 Secondary outcome 1: 90-day all-cause mortality
e_evt_death <- c(69, 10, 55, 8, 21, 18)
n_evt_death <- c(327, 116, 270, 103, 201, 146)
e_br_death  <- c(66, 14, 42, 9, 25, 16)
n_br_death  <- c(329, 118, 264, 101, 207, 149)

# 1.3 Secondary outcome 2: sICH
e_evt_sich <- c(14, 7, 16, 6, 5, 4)
n_evt_sich <- c(327, 116, 270, 103, 201, 146)
e_br_sich  <- c(15, 4, 14, 8, 7, 4)
n_br_sich  <- c(329, 118, 264, 101, 207, 149)

# 1.4 Secondary outcome 3: Successful reperfusion mTICI 2b-3
e_evt_recan <- c(260, 91, 217, 87, 185, 130)
n_evt_recan <- c(327, 116, 270, 103, 201, 146)
e_br_recan  <- c(278, 95, 221, 88, 189, 135)
n_br_recan  <- c(329, 118, 264, 101, 207, 149)

# --- 2. Primary Outcome: Main Analysis -----------------------
# Random-effects model with DerSimonian-Laird + Knapp-Hartung
# Effect measure: Odds Ratio (OR), log-transformed

# 2.1 Calculate individual study log(OR) and variance
dat_primary <- escalc(
  measure = "OR",
  ai = e_evt,  n1i = n_evt,
  ci = e_br,   n2i = n_br,
  slab = study
)

# 2.2 Fit random-effects model (DL + HKSJ)
res_primary_dl <- rma(yi, vi, data = dat_primary,
                      method = "DL",
                      test = "knha",
                      slab = study)

# 2.3 Fit random-effects model (REML + HKSJ) for sensitivity
res_primary_reml <- rma(yi, vi, data = dat_primary,
                        method = "REML",
                        test = "knha",
                        slab = study)

# 2.4 Fit fixed-effect model (Mantel-Haenszel) for sensitivity
res_primary_fe <- rma.mh(
  ai = e_evt, n1i = n_evt,
  ci = e_br,  n2i = n_br,
  measure = "OR",
  slab = study
)

# --- 3. Primary Outcome: Forest Plot -------------------------

# Print summary for reference
cat("\n============================================================\n")
cat("PRIMARY OUTCOME: 90-day mRS 0-2 (Functional Independence)\n")
cat("Random-effects model (DL + HKSJ)\n")
cat("============================================================\n")
print(res_primary_dl)

cat("\nPrediction interval (DL):\n")
pi_dl <- predict(res_primary_dl)
cat(sprintf("  95%% PI: [%.4f, %.4f] on log(OR) scale\n", pi_dl$pi.lb, pi_dl$pi.ub))
cat(sprintf("  95%% PI: [%.2f, %.2f] on OR scale\n", exp(pi_dl$pi.lb), exp(pi_dl$pi.ub)))

# 3.1 Forest plot for primary outcome (PDF output)
pdf("/Users/admin/Downloads/meta_writing/forest_primary_mRS02.pdf",
    width = 12, height = 7)

forest(res_primary_dl,
       atransf = exp,
       at = log(c(0.5, 0.7, 0.82, 1.0, 1.5, 2.0)),
       xlim = c(-3.5, 3.0),
       ilab = cbind(
         paste0(e_evt, "/", n_evt),
         paste0(e_br, "/", n_br)
       ),
       ilab.xpos = c(-2.0, -1.3),
       ilab.pos = c(2, 2),
       cex = 0.85,
       header = TRUE,
       mlab = paste0(
         "Random-effects model (DL + HKSJ): OR = ",
         formatC(exp(res_primary_dl$beta), format = "f", digits = 2),
         " [95% CI: ",
         formatC(exp(res_primary_dl$ci.lb), format = "f", digits = 2),
         ", ",
         formatC(exp(res_primary_dl$ci.ub), format = "f", digits = 2),
         "]; p = ",
         formatC(res_primary_dl$pval, format = "f", digits = 3)
       ),
       xlab = "Odds Ratio (Direct EVT vs. Bridging)",
       refline = 0,
       digits = 2L,
       showweights = TRUE
)

# Add column labels
text(c(-2.0, -1.3), res_primary_dl$k + 1.5,
     c("Direct EVT\n(n/N)", "Bridging\n(n/N)"),
     font = 2, cex = 0.75, pos = 2)

# Add non-inferiority margin line (OR = 0.82)
abline(v = log(0.82), lty = 2, col = "red", lwd = 1.5)
text(log(0.82), res_primary_dl$k + 2.0,
     "NI margin\n(OR = 0.82)",
     col = "red", cex = 0.65, font = 3, pos = 4)

# Add prediction interval annotation
text(-3.5, -2.5,
     paste0("Prediction interval: [",
            formatC(exp(pi_dl$pi.lb), format = "f", digits = 2),
            ", ",
            formatC(exp(pi_dl$pi.ub), format = "f", digits = 2),
            "]"),
     cex = 0.75, pos = 4, font = 3)

# Add heterogeneity annotation
text(-3.5, -3.2,
     paste0("Heterogeneity: Q = ",
            formatC(res_primary_dl$QE, format = "f", digits = 2),
            " (df = ", res_primary_dl$k - 1,
            ", p = ", formatC(res_primary_dl$QEp, format = "f", digits = 3),
            "); I-squared = ",
            formatC(res_primary_dl$I2, format = "f", digits = 1),
            "%; tau-squared = ",
            formatC(res_primary_dl$tau2, format = "f", digits = 4)),
     cex = 0.70, pos = 4, font = 1)

# Arrow annotations for direction
text(log(0.5), -4, "Favors Bridging", cex = 0.70, font = 3)
text(log(2.0), -4, "Favors Direct EVT", cex = 0.70, font = 3)

dev.off()
cat("\nPrimary forest plot saved to: /Users/admin/Downloads/meta_writing/forest_primary_mRS02.pdf\n")


# --- 4. Secondary Outcome Forest Plots -----------------------

# 4.1 90-day All-Cause Mortality
dat_death <- escalc(
  measure = "OR",
  ai = e_evt_death, n1i = n_evt_death,
  ci = e_br_death,  n2i = n_br_death,
  slab = study
)

res_death_dl <- rma(yi, vi, data = dat_death,
                    method = "DL", test = "knha", slab = study)

cat("\n============================================================\n")
cat("SECONDARY OUTCOME 1: 90-day All-Cause Mortality\n")
cat("============================================================\n")
print(res_death_dl)

pi_death <- predict(res_death_dl)

pdf("/Users/admin/Downloads/meta_writing/forest_mortality.pdf",
    width = 12, height = 7)

forest(res_death_dl,
       atransf = exp,
       at = log(c(0.3, 0.5, 0.7, 1.0, 1.5, 2.0, 3.0)),
       xlim = c(-3.5, 3.5),
       ilab = cbind(
         paste0(e_evt_death, "/", n_evt_death),
         paste0(e_br_death, "/", n_br_death)
       ),
       ilab.xpos = c(-2.0, -1.3),
       ilab.pos = c(2, 2),
       cex = 0.85,
       header = TRUE,
       mlab = paste0(
         "RE model (DL + HKSJ): OR = ",
         formatC(exp(res_death_dl$beta), format = "f", digits = 2),
         " [95% CI: ",
         formatC(exp(res_death_dl$ci.lb), format = "f", digits = 2),
         ", ",
         formatC(exp(res_death_dl$ci.ub), format = "f", digits = 2),
         "]"
       ),
       xlab = "Odds Ratio (Direct EVT vs. Bridging) -- Mortality",
       refline = 0,
       digits = 2L,
       showweights = TRUE
)

text(c(-2.0, -1.3), res_death_dl$k + 1.5,
     c("Direct EVT\n(deaths/N)", "Bridging\n(deaths/N)"),
     font = 2, cex = 0.75, pos = 2)

text(-3.5, -2.5,
     paste0("Prediction interval: [",
            formatC(exp(pi_death$pi.lb), format = "f", digits = 2),
            ", ",
            formatC(exp(pi_death$pi.ub), format = "f", digits = 2),
            "]"),
     cex = 0.75, pos = 4, font = 3)

text(-3.5, -3.2,
     paste0("Heterogeneity: Q = ",
            formatC(res_death_dl$QE, format = "f", digits = 2),
            " (df = ", res_death_dl$k - 1,
            ", p = ", formatC(res_death_dl$QEp, format = "f", digits = 3),
            "); I-squared = ",
            formatC(res_death_dl$I2, format = "f", digits = 1),
            "%; tau-squared = ",
            formatC(res_death_dl$tau2, format = "f", digits = 4)),
     cex = 0.70, pos = 4)

text(log(0.3), -4, "Favors Direct EVT", cex = 0.70, font = 3)
text(log(3.0), -4, "Favors Bridging", cex = 0.70, font = 3)

dev.off()
cat("Mortality forest plot saved to: /Users/admin/Downloads/meta_writing/forest_mortality.pdf\n")


# 4.2 Symptomatic Intracranial Hemorrhage (sICH)
dat_sich <- escalc(
  measure = "OR",
  ai = e_evt_sich, n1i = n_evt_sich,
  ci = e_br_sich,  n2i = n_br_sich,
  slab = study
)

res_sich_dl <- rma(yi, vi, data = dat_sich,
                   method = "DL", test = "knha", slab = study)

cat("\n============================================================\n")
cat("SECONDARY OUTCOME 2: Symptomatic ICH (sICH)\n")
cat("============================================================\n")
print(res_sich_dl)

pi_sich <- predict(res_sich_dl)

pdf("/Users/admin/Downloads/meta_writing/forest_sICH.pdf",
    width = 12, height = 7)

forest(res_sich_dl,
       atransf = exp,
       at = log(c(0.2, 0.5, 1.0, 2.0, 5.0)),
       xlim = c(-4.0, 4.0),
       ilab = cbind(
         paste0(e_evt_sich, "/", n_evt_sich),
         paste0(e_br_sich, "/", n_br_sich)
       ),
       ilab.xpos = c(-2.2, -1.5),
       ilab.pos = c(2, 2),
       cex = 0.85,
       header = TRUE,
       mlab = paste0(
         "RE model (DL + HKSJ): OR = ",
         formatC(exp(res_sich_dl$beta), format = "f", digits = 2),
         " [95% CI: ",
         formatC(exp(res_sich_dl$ci.lb), format = "f", digits = 2),
         ", ",
         formatC(exp(res_sich_dl$ci.ub), format = "f", digits = 2),
         "]"
       ),
       xlab = "Odds Ratio (Direct EVT vs. Bridging) -- sICH",
       refline = 0,
       digits = 2L,
       showweights = TRUE
)

text(c(-2.2, -1.5), res_sich_dl$k + 1.5,
     c("Direct EVT\n(sICH/N)", "Bridging\n(sICH/N)"),
     font = 2, cex = 0.75, pos = 2)

text(-4.0, -2.5,
     paste0("Prediction interval: [",
            formatC(exp(pi_sich$pi.lb), format = "f", digits = 2),
            ", ",
            formatC(exp(pi_sich$pi.ub), format = "f", digits = 2),
            "]"),
     cex = 0.75, pos = 4, font = 3)

text(-4.0, -3.2,
     paste0("Heterogeneity: Q = ",
            formatC(res_sich_dl$QE, format = "f", digits = 2),
            " (df = ", res_sich_dl$k - 1,
            ", p = ", formatC(res_sich_dl$QEp, format = "f", digits = 3),
            "); I-squared = ",
            formatC(res_sich_dl$I2, format = "f", digits = 1),
            "%; tau-squared = ",
            formatC(res_sich_dl$tau2, format = "f", digits = 4)),
     cex = 0.70, pos = 4)

# Note: OR > 1 means more sICH in Direct EVT
text(log(0.2), -4, "Favors Direct EVT", cex = 0.70, font = 3)
text(log(5.0), -4, "Favors Bridging", cex = 0.70, font = 3)

dev.off()
cat("sICH forest plot saved to: /Users/admin/Downloads/meta_writing/forest_sICH.pdf\n")


# 4.3 Successful Reperfusion (mTICI 2b-3)
dat_recan <- escalc(
  measure = "OR",
  ai = e_evt_recan, n1i = n_evt_recan,
  ci = e_br_recan,  n2i = n_br_recan,
  slab = study
)

res_recan_dl <- rma(yi, vi, data = dat_recan,
                    method = "DL", test = "knha", slab = study)

cat("\n============================================================\n")
cat("SECONDARY OUTCOME 3: Successful Reperfusion (mTICI 2b-3)\n")
cat("============================================================\n")
print(res_recan_dl)

pi_recan <- predict(res_recan_dl)

pdf("/Users/admin/Downloads/meta_writing/forest_reperfusion.pdf",
    width = 12, height = 7)

forest(res_recan_dl,
       atransf = exp,
       at = log(c(0.3, 0.5, 0.7, 1.0, 1.5, 2.0)),
       xlim = c(-3.5, 3.5),
       ilab = cbind(
         paste0(e_evt_recan, "/", n_evt_recan),
         paste0(e_br_recan, "/", n_br_recan)
       ),
       ilab.xpos = c(-2.0, -1.3),
       ilab.pos = c(2, 2),
       cex = 0.85,
       header = TRUE,
       mlab = paste0(
         "RE model (DL + HKSJ): OR = ",
         formatC(exp(res_recan_dl$beta), format = "f", digits = 2),
         " [95% CI: ",
         formatC(exp(res_recan_dl$ci.lb), format = "f", digits = 2),
         ", ",
         formatC(exp(res_recan_dl$ci.ub), format = "f", digits = 2),
         "]"
       ),
       xlab = "Odds Ratio (Direct EVT vs. Bridging) -- mTICI 2b-3",
       refline = 0,
       digits = 2L,
       showweights = TRUE
)

text(c(-2.0, -1.3), res_recan_dl$k + 1.5,
     c("Direct EVT\n(mTICI 2b-3/N)", "Bridging\n(mTICI 2b-3/N)"),
     font = 2, cex = 0.75, pos = 2)

text(-3.5, -2.5,
     paste0("Prediction interval: [",
            formatC(exp(pi_recan$pi.lb), format = "f", digits = 2),
            ", ",
            formatC(exp(pi_recan$pi.ub), format = "f", digits = 2),
            "]"),
     cex = 0.75, pos = 4, font = 3)

text(-3.5, -3.2,
     paste0("Heterogeneity: Q = ",
            formatC(res_recan_dl$QE, format = "f", digits = 2),
            " (df = ", res_recan_dl$k - 1,
            ", p = ", formatC(res_recan_dl$QEp, format = "f", digits = 3),
            "); I-squared = ",
            formatC(res_recan_dl$I2, format = "f", digits = 1),
            "%; tau-squared = ",
            formatC(res_recan_dl$tau2, format = "f", digits = 4)),
     cex = 0.70, pos = 4)

text(log(0.3), -4, "Favors Bridging", cex = 0.70, font = 3)
text(log(2.0), -4, "Favors Direct EVT", cex = 0.70, font = 3)

dev.off()
cat("Reperfusion forest plot saved to: /Users/admin/Downloads/meta_writing/forest_reperfusion.pdf\n")


# --- 5. Sensitivity Analysis: Leave-One-Out -------------------

cat("\n============================================================\n")
cat("SENSITIVITY ANALYSIS: Leave-One-Out (Primary Outcome)\n")
cat("============================================================\n")

loo_results <- leave1out(res_primary_dl)
print(loo_results)

# Forest plot for leave-one-out analysis
pdf("/Users/admin/Downloads/meta_writing/forest_leave1out.pdf",
    width = 10, height = 6)

# Manually create leave-one-out forest plot
loo_or  <- exp(loo_results$estimate)
loo_lb  <- exp(loo_results$ci.lb)
loo_ub  <- exp(loo_results$ci.ub)
loo_lab <- paste0("Omitting: ", study)

par(mar = c(5, 1, 3, 1))
forest(
  x = loo_results$estimate,
  vi = ((loo_results$ci.ub - loo_results$ci.lb) / (2 * qnorm(0.975)))^2,
  slab = loo_lab,
  atransf = exp,
  at = log(c(0.7, 0.82, 1.0, 1.2, 1.5)),
  xlim = c(-2.0, 2.0),
  xlab = "Pooled OR (leave-one-out)",
  cex = 0.85,
  header = "Leave-One-Out Analysis (Primary Outcome: mRS 0-2)",
  refline = 0,
  digits = 2L
)

# Add reference lines
abline(v = res_primary_dl$beta, lty = 3, col = "blue", lwd = 1)
abline(v = log(0.82), lty = 2, col = "red", lwd = 1.5)
text(log(0.82), 7.5, "NI margin\n(OR=0.82)", col = "red", cex = 0.60, font = 3, pos = 2)

dev.off()
cat("Leave-one-out forest plot saved to: /Users/admin/Downloads/meta_writing/forest_leave1out.pdf\n")


# --- 6. Sensitivity Analysis: Fixed-Effect vs Random-Effects --

cat("\n============================================================\n")
cat("SENSITIVITY ANALYSIS: Fixed-Effect Model (MH) vs RE Model\n")
cat("============================================================\n")

cat("\nRandom-effects model (DL + HKSJ):\n")
cat(sprintf("  OR = %.2f [95%% CI: %.2f, %.2f], p = %.4f\n",
            exp(res_primary_dl$beta), exp(res_primary_dl$ci.lb),
            exp(res_primary_dl$ci.ub), res_primary_dl$pval))

cat("\nRandom-effects model (REML + HKSJ):\n")
cat(sprintf("  OR = %.2f [95%% CI: %.2f, %.2f], p = %.4f\n",
            exp(res_primary_reml$beta), exp(res_primary_reml$ci.lb),
            exp(res_primary_reml$ci.ub), res_primary_reml$pval))

cat("\nFixed-effect model (Mantel-Haenszel):\n")
cat(sprintf("  OR = %.2f [95%% CI: %.2f, %.2f], p = %.4f\n",
            exp(res_primary_fe$beta), exp(res_primary_fe$ci.lb),
            exp(res_primary_fe$ci.ub), res_primary_fe$pval))

# Combined sensitivity forest plot: FE vs RE comparison
pdf("/Users/admin/Downloads/meta_writing/forest_sensitivity_FE_vs_RE.pdf",
    width = 12, height = 8)

# Plot individual studies + both model estimates
forest(res_primary_dl,
       atransf = exp,
       at = log(c(0.5, 0.7, 0.82, 1.0, 1.5, 2.0)),
       xlim = c(-3.5, 3.0),
       ilab = cbind(
         paste0(e_evt, "/", n_evt),
         paste0(e_br, "/", n_br)
       ),
       ilab.xpos = c(-2.0, -1.3),
       ilab.pos = c(2, 2),
       cex = 0.80,
       header = TRUE,
       mlab = paste0(
         "Random-effects (DL + HKSJ): OR = ",
         formatC(exp(res_primary_dl$beta), format = "f", digits = 2),
         " [",
         formatC(exp(res_primary_dl$ci.lb), format = "f", digits = 2),
         ", ",
         formatC(exp(res_primary_dl$ci.ub), format = "f", digits = 2),
         "]"
       ),
       xlab = "Odds Ratio (Direct EVT vs. Bridging)",
       refline = 0,
       digits = 2L,
       showweights = TRUE
)

# Add FE result as additional row
addpoly(res_primary_fe, row = -2.5, atransf = exp,
        mlab = paste0(
          "Fixed-effect (MH): OR = ",
          formatC(exp(res_primary_fe$beta), format = "f", digits = 2),
          " [",
          formatC(exp(res_primary_fe$ci.lb), format = "f", digits = 2),
          ", ",
          formatC(exp(res_primary_fe$ci.ub), format = "f", digits = 2),
          "]"
        ),
        cex = 0.80, col = "darkblue")

# Add REML result
addpoly(res_primary_reml, row = -4.0, atransf = exp,
        mlab = paste0(
          "Random-effects (REML + HKSJ): OR = ",
          formatC(exp(res_primary_reml$beta), format = "f", digits = 2),
          " [",
          formatC(exp(res_primary_reml$ci.lb), format = "f", digits = 2),
          ", ",
          formatC(exp(res_primary_reml$ci.ub), format = "f", digits = 2),
          "]"
        ),
        cex = 0.80, col = "darkgreen")

text(c(-2.0, -1.3), res_primary_dl$k + 1.5,
     c("Direct EVT\n(n/N)", "Bridging\n(n/N)"),
     font = 2, cex = 0.70, pos = 2)

abline(v = log(0.82), lty = 2, col = "red", lwd = 1.5)
text(log(0.82), res_primary_dl$k + 2.0,
     "NI margin (OR=0.82)", col = "red", cex = 0.60, font = 3, pos = 4)

dev.off()
cat("FE vs RE sensitivity forest plot saved to: /Users/admin/Downloads/meta_writing/forest_sensitivity_FE_vs_RE.pdf\n")


# --- 7. Influence Diagnostics (Primary Outcome) ---------------

cat("\n============================================================\n")
cat("INFLUENCE DIAGNOSTICS (Primary Outcome)\n")
cat("============================================================\n")

inf_primary <- influence(res_primary_dl)
print(inf_primary)

pdf("/Users/admin/Downloads/meta_writing/influence_diagnostics.pdf",
    width = 10, height = 10)
plot(inf_primary)
dev.off()
cat("Influence diagnostics plot saved to: /Users/admin/Downloads/meta_writing/influence_diagnostics.pdf\n")


# --- 8. Subgroup Analysis: Geographic Region ------------------

cat("\n============================================================\n")
cat("SUBGROUP ANALYSIS: Geographic Region (Asian vs. Non-Asian)\n")
cat("============================================================\n")

# Region classification
# Asian: DIRECT-MT (China), DEVT (China), SKIP (Japan)
# Non-Asian: MR CLEAN-NO IV (Netherlands/Europe), SWIFT DIRECT (Europe/Canada)
# Mixed: DIRECT-SAFE (Australia + China) -- classified as mixed/non-Asian for this analysis
region <- c("Asian", "Asian", "Non-Asian", "Asian", "Non-Asian", "Non-Asian")

dat_primary$region <- region

# Mixed-effects model for subgroup analysis
res_subgroup_region <- rma(yi, vi, data = dat_primary,
                           method = "DL", test = "knha",
                           mods = ~ region)

cat("\nTest for subgroup differences (region):\n")
print(res_subgroup_region)

# Separate models for each region
res_asian    <- rma(yi, vi, data = dat_primary, method = "DL", test = "knha",
                    subset = (region == "Asian"))
res_nonasian <- rma(yi, vi, data = dat_primary, method = "DL", test = "knha",
                    subset = (region == "Non-Asian"))

cat("\nAsian subgroup:\n")
cat(sprintf("  OR = %.2f [95%% CI: %.2f, %.2f], k = %d\n",
            exp(res_asian$beta), exp(res_asian$ci.lb),
            exp(res_asian$ci.ub), res_asian$k))

cat("\nNon-Asian subgroup:\n")
cat(sprintf("  OR = %.2f [95%% CI: %.2f, %.2f], k = %d\n",
            exp(res_nonasian$beta), exp(res_nonasian$ci.lb),
            exp(res_nonasian$ci.ub), res_nonasian$k))

# Subgroup forest plot
pdf("/Users/admin/Downloads/meta_writing/forest_subgroup_region.pdf",
    width = 12, height = 9)

# Use meta package for cleaner subgroup forest plot
m_subgroup <- metabin(
  event.e = e_evt, n.e = n_evt,
  event.c = e_br, n.c = n_br,
  studlab = study,
  sm = "OR",
  method.tau = "DL",
  hakn = TRUE,
  subgroup = region,
  test.subgroup = TRUE,
  print.subgroup.name = TRUE
)

forest(m_subgroup,
       sortvar = region,
       print.tau2 = TRUE,
       print.I2 = TRUE,
       print.pval.Q = TRUE,
       prediction = TRUE,
       label.left = "Favors Bridging",
       label.right = "Favors Direct EVT",
       col.diamond = "blue",
       col.diamond.lines = "blue",
       col.predict = "darkred",
       smlab = "Odds Ratio (mRS 0-2)\nDirect EVT vs. Bridging",
       leftcols = c("studlab", "event.e", "n.e", "event.c", "n.c"),
       leftlabs = c("Study", "Events", "Total", "Events", "Total"),
       rightcols = c("effect", "ci", "w.random"),
       rightlabs = c("OR", "95% CI", "Weight"),
       just.addcols = "right",
       comb.fixed = FALSE,
       comb.random = TRUE,
       overall = TRUE,
       test.subgroup.random = TRUE,
       hetstat = TRUE,
       overall.hetstat = TRUE,
       xlim = c(0.4, 2.5),
       ref = 1
)

dev.off()
cat("Subgroup forest plot saved to: /Users/admin/Downloads/meta_writing/forest_subgroup_region.pdf\n")


# --- 9. Summary Table of All Outcomes -------------------------

cat("\n============================================================\n")
cat("SUMMARY OF ALL OUTCOMES\n")
cat("============================================================\n")

outcomes <- c("mRS 0-2", "Mortality", "sICH", "mTICI 2b-3")
models   <- list(res_primary_dl, res_death_dl, res_sich_dl, res_recan_dl)

cat("\n%-25s  %6s  %13s  %8s  %6s  %6s\n",
    "Outcome", "OR", "95% CI", "p-value", "I2(%)", "tau2")
cat(paste(rep("-", 80), collapse = ""), "\n")

for (i in seq_along(outcomes)) {
  m <- models[[i]]
  cat(sprintf("%-25s  %6.2f  [%5.2f, %5.2f]  %8.4f  %6.1f  %6.4f\n",
              outcomes[i],
              exp(m$beta),
              exp(m$ci.lb),
              exp(m$ci.ub),
              m$pval,
              m$I2,
              m$tau2))
}


# --- 10. Session Info -----------------------------------------

cat("\n============================================================\n")
cat("SESSION INFORMATION\n")
cat("============================================================\n")
sessionInfo()
