# ============================================================
# FUNNEL PLOT & PUBLICATION BIAS ASSESSMENT
# Direct EVT vs. Bridging Therapy for Acute LVO Ischemic Stroke
# Generated by: Statistician Agent
# Date: 2026-02-26
# ============================================================
#
# IMPORTANT CAVEAT:
# This analysis includes only k = 6 studies. Funnel-plot-based
# tests (Egger's, Begg's) have very low statistical power when
# k < 10 (Cochrane Handbook Section 10.4.3). Results from these
# tests should be interpreted with extreme caution and are
# considered exploratory only. The visual assessment of funnel
# plot symmetry is also unreliable with so few studies.
# ============================================================

# --- 0. Setup & Package Checks --------------------------------

ensure_packages <- function(pkgs) {
  for (pkg in pkgs) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      install.packages(pkg, repos = "https://cloud.r-project.org")
    }
    library(pkg, character.only = TRUE)
  }
}

ensure_packages(c("metafor", "meta"))

# --- 1. Data Input --------------------------------------------

study <- c(
  "DIRECT-MT (Yang 2020)",
  "DEVT (Zi 2021)",
  "MR CLEAN-NO IV (LeCouffe 2021)",
  "SKIP (Suzuki 2021)",
  "SWIFT DIRECT (Fischer 2022)",
  "DIRECT-SAFE (Mitchell 2022)"
)

# Primary outcome: 90-day mRS 0-2
e_evt <- c(119, 63, 138, 61, 131, 84)
n_evt <- c(327, 116, 270, 103, 201, 146)
e_br  <- c(121, 55, 139, 58, 127, 82)
n_br  <- c(329, 118, 264, 101, 207, 149)

# Calculate log(OR) and sampling variance
dat <- escalc(
  measure = "OR",
  ai = e_evt, n1i = n_evt,
  ci = e_br,  n2i = n_br,
  slab = study
)

# Fit primary model (DL + HKSJ)
res <- rma(yi, vi, data = dat, method = "DL", test = "knha")

# --- 2. Standard Funnel Plot ----------------------------------

cat("\n============================================================\n")
cat("PUBLICATION BIAS ASSESSMENT: PRIMARY OUTCOME (mRS 0-2)\n")
cat("============================================================\n")
cat("\nCAVEAT: k = 6 studies (<10). All publication bias tests have\n")
cat("low statistical power. Results are EXPLORATORY only.\n")
cat("============================================================\n\n")

# 2.1 Standard funnel plot with pseudo-95% CI lines
pdf("/Users/admin/Downloads/meta_writing/funnel_primary.pdf",
    width = 8, height = 7)

funnel(res,
       xlab = "Log Odds Ratio (Direct EVT vs. Bridging)",
       main = "Funnel Plot: 90-day mRS 0-2 (k = 6)",
       level = c(90, 95, 99),
       shade = c("white", "gray85", "gray70"),
       refline = res$beta,
       legend = TRUE,
       back = "gray95",
       hlines = NULL,
       digits = 2L)

# Add study labels
text(dat$yi, sqrt(dat$vi),
     labels = c("DIRECT-MT", "DEVT", "MR CLEAN-NO IV",
                "SKIP", "SWIFT DIRECT", "DIRECT-SAFE"),
     pos = 4, cex = 0.60, col = "darkblue")

# Add caveat text
mtext("CAVEAT: k = 6 (<10); visual and statistical tests have low power",
      side = 1, line = 4, cex = 0.70, font = 3, col = "red")

dev.off()
cat("Standard funnel plot saved to: /Users/admin/Downloads/meta_writing/funnel_primary.pdf\n")


# 2.2 Contour-enhanced funnel plot
pdf("/Users/admin/Downloads/meta_writing/funnel_contour.pdf",
    width = 8, height = 7)

funnel(res,
       xlab = "Log Odds Ratio (Direct EVT vs. Bridging)",
       main = "Contour-Enhanced Funnel Plot: 90-day mRS 0-2 (k = 6)",
       level = c(0.05, 0.01, 0.001),
       shade = c("white", "gray80", "gray60"),
       refline = 0,
       legend = TRUE,
       back = "gray95",
       digits = 2L)

text(dat$yi, sqrt(dat$vi),
     labels = c("DIRECT-MT", "DEVT", "MR CLEAN-NO IV",
                "SKIP", "SWIFT DIRECT", "DIRECT-SAFE"),
     pos = 4, cex = 0.60, col = "darkblue")

mtext("CAVEAT: k = 6 (<10); tests have low power",
      side = 1, line = 4, cex = 0.70, font = 3, col = "red")

dev.off()
cat("Contour-enhanced funnel plot saved to: /Users/admin/Downloads/meta_writing/funnel_contour.pdf\n")


# --- 3. Egger's Regression Test -------------------------------

cat("\n--- 3. Egger's Regression Test ---\n")
cat("NOTE: With k = 6, Egger's test has insufficient power to\n")
cat("detect small-study effects. The recommended minimum is k >= 10.\n\n")

egger_test <- regtest(res, model = "lm", predictor = "sei")
cat("Egger's regression test results:\n")
print(egger_test)

cat(sprintf("\n  Intercept (bias coefficient): z = %.3f, p = %.4f\n",
            egger_test$zval, egger_test$pval))

if (egger_test$pval < 0.10) {
  cat("  Interpretation: Statistically significant funnel plot asymmetry\n")
  cat("  detected (p < 0.10). However, given k = 6, this result has low\n")
  cat("  reliability and should be interpreted with extreme caution.\n")
} else {
  cat("  Interpretation: No statistically significant funnel plot\n")
  cat("  asymmetry detected. However, given k = 6, the test lacks power\n")
  cat("  to rule out publication bias.\n")
}


# --- 4. Begg's Rank Correlation Test --------------------------

cat("\n--- 4. Begg's Rank Correlation Test ---\n")
cat("NOTE: With k = 6, Begg's test is even less powerful than Egger's.\n\n")

begg_test <- ranktest(res)
cat("Begg and Mazumdar rank correlation test results:\n")
print(begg_test)

cat(sprintf("\n  Kendall's tau = %.3f, p = %.4f\n",
            begg_test$tau, begg_test$pval))

if (begg_test$pval < 0.10) {
  cat("  Interpretation: Significant rank correlation detected,\n")
  cat("  suggesting potential publication bias. However, k = 6\n")
  cat("  severely limits reliability.\n")
} else {
  cat("  Interpretation: No significant rank correlation detected.\n")
  cat("  Insufficient power to draw definitive conclusions (k = 6).\n")
}


# --- 5. Peters' Regression Test (for binary outcomes) ---------
# Peters' test is preferred over Egger's for binary OR/RR measures
# because Egger's can produce artefactual asymmetry with binary data.

cat("\n--- 5. Peters' Regression Test ---\n")
cat("NOTE: Peters' test uses 1/N as the predictor, which is more\n")
cat("appropriate for binary outcomes (OR). Still limited by k = 6.\n\n")

peters_test <- regtest(res, model = "lm", predictor = "ni")
cat("Peters' regression test results:\n")
print(peters_test)

cat(sprintf("\n  Test statistic: z = %.3f, p = %.4f\n",
            peters_test$zval, peters_test$pval))


# --- 6. Trim-and-Fill Method ----------------------------------

cat("\n--- 6. Trim-and-Fill Analysis ---\n")
cat("NOTE: Trim-and-fill with k = 6 is highly uncertain.\n")
cat("Results are purely exploratory.\n\n")

# Left side (looking for missing studies that favor bridging)
tf_left <- trimfill(res, side = "left")
cat("Trim-and-fill (left side -- missing studies favoring bridging):\n")
print(tf_left)
cat(sprintf("\n  Estimated missing studies (left): k0 = %d\n", tf_left$k0))
cat(sprintf("  Adjusted pooled OR = %.2f [95%% CI: %.2f, %.2f]\n",
            exp(tf_left$beta), exp(tf_left$ci.lb), exp(tf_left$ci.ub)))

# Right side (looking for missing studies that favor Direct EVT)
tf_right <- trimfill(res, side = "right")
cat("\nTrim-and-fill (right side -- missing studies favoring Direct EVT):\n")
print(tf_right)
cat(sprintf("\n  Estimated missing studies (right): k0 = %d\n", tf_right$k0))
cat(sprintf("  Adjusted pooled OR = %.2f [95%% CI: %.2f, %.2f]\n",
            exp(tf_right$beta), exp(tf_right$ci.lb), exp(tf_right$ci.ub)))

# Funnel plot with trim-and-fill
pdf("/Users/admin/Downloads/meta_writing/funnel_trimfill.pdf",
    width = 10, height = 7)

par(mfrow = c(1, 2))

# Left side trim-and-fill
funnel(tf_left,
       xlab = "Log Odds Ratio",
       main = paste0("Trim-and-Fill (Left): k0 = ", tf_left$k0),
       level = 95,
       shade = "gray85",
       refline = tf_left$beta,
       legend = TRUE,
       digits = 2L)
mtext("k = 6; results exploratory", side = 1, line = 3.5,
      cex = 0.65, font = 3, col = "red")

# Right side trim-and-fill
funnel(tf_right,
       xlab = "Log Odds Ratio",
       main = paste0("Trim-and-Fill (Right): k0 = ", tf_right$k0),
       level = 95,
       shade = "gray85",
       refline = tf_right$beta,
       legend = TRUE,
       digits = 2L)
mtext("k = 6; results exploratory", side = 1, line = 3.5,
      cex = 0.65, font = 3, col = "red")

par(mfrow = c(1, 1))

dev.off()
cat("\nTrim-and-fill funnel plot saved to: /Users/admin/Downloads/meta_writing/funnel_trimfill.pdf\n")


# --- 7. Publication Bias Assessment for Secondary Outcomes ----
# (Brief assessment, same caveat applies: k = 6)

cat("\n============================================================\n")
cat("PUBLICATION BIAS: SECONDARY OUTCOMES (brief, k = 6 caveat)\n")
cat("============================================================\n")

# 7.1 Mortality
dat_death <- escalc(
  measure = "OR",
  ai = c(69, 10, 55, 8, 21, 18),
  n1i = c(327, 116, 270, 103, 201, 146),
  ci = c(66, 14, 42, 9, 25, 16),
  n2i = c(329, 118, 264, 101, 207, 149),
  slab = study
)
res_death <- rma(yi, vi, data = dat_death, method = "DL", test = "knha")

egger_death <- regtest(res_death, model = "lm", predictor = "sei")
cat("\nMortality -- Egger's test: z =", round(egger_death$zval, 3),
    ", p =", round(egger_death$pval, 4), "\n")

# 7.2 sICH
dat_sich <- escalc(
  measure = "OR",
  ai = c(14, 7, 16, 6, 5, 4),
  n1i = c(327, 116, 270, 103, 201, 146),
  ci = c(15, 4, 14, 8, 7, 4),
  n2i = c(329, 118, 264, 101, 207, 149),
  slab = study
)
res_sich <- rma(yi, vi, data = dat_sich, method = "DL", test = "knha")

egger_sich <- regtest(res_sich, model = "lm", predictor = "sei")
cat("sICH -- Egger's test: z =", round(egger_sich$zval, 3),
    ", p =", round(egger_sich$pval, 4), "\n")

# 7.3 Reperfusion
dat_recan <- escalc(
  measure = "OR",
  ai = c(260, 91, 217, 87, 185, 130),
  n1i = c(327, 116, 270, 103, 201, 146),
  ci = c(278, 95, 221, 88, 189, 135),
  n2i = c(329, 118, 264, 101, 207, 149),
  slab = study
)
res_recan <- rma(yi, vi, data = dat_recan, method = "DL", test = "knha")

egger_recan <- regtest(res_recan, model = "lm", predictor = "sei")
cat("mTICI 2b-3 -- Egger's test: z =", round(egger_recan$zval, 3),
    ", p =", round(egger_recan$pval, 4), "\n")

cat("\nAll secondary outcome tests should be interpreted with k = 6 caveat.\n")


# --- 8. Summary Table -----------------------------------------

cat("\n============================================================\n")
cat("PUBLICATION BIAS SUMMARY TABLE\n")
cat("============================================================\n\n")

cat(sprintf("%-20s  %-15s  %-15s  %-10s  %-20s\n",
            "Outcome", "Egger p-value", "Begg p-value",
            "TF k0 (L/R)", "TF adjusted OR"))
cat(paste(rep("-", 85), collapse = ""), "\n")

# Primary outcome
cat(sprintf("%-20s  p = %-10.4f  p = %-10.4f  %d / %d        %.2f [%.2f, %.2f]\n",
            "mRS 0-2",
            egger_test$pval,
            begg_test$pval,
            tf_left$k0, tf_right$k0,
            exp(tf_left$beta), exp(tf_left$ci.lb), exp(tf_left$ci.ub)))

cat("\n* All tests performed with k = 6 studies (<10 recommended minimum).\n")
cat("* Results are EXPLORATORY and should NOT be used for definitive\n")
cat("  conclusions about the presence or absence of publication bias.\n")
cat("* The small number of studies reflects the fact that only 6 RCTs\n")
cat("  comparing direct EVT vs. bridging therapy have been published.\n")


# --- 9. Session Info ------------------------------------------

cat("\n============================================================\n")
cat("SESSION INFORMATION\n")
cat("============================================================\n")
sessionInfo()
